/***************************************************************************
 Name          : ALM_Model_User_SalesLeader
 Created By    : Fay Salwen
 Description   : Concrete model class for Sales Leader users
 Created Date  : Feb 19, 2014               
****************************************************************************/

public with sharing class ALM_Model_User_SalesLeader extends ALM_Model_User {

}