/***************************************************************************
 Name          : Controller_ALMCampaignFocus 
 Created By    : Parul Gupta
 Created Date  : Dec 12, 2013 
 Description   : Copy of ZM_CampaignFocusController             
****************************************************************************/
public class Controller_SLHomePage {
	Public Controller_SLHomePage(){
		
	}
}